# Generated by Django 5.1.6 on 2025-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbcModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        default="Даны вещественные положительные числа a, b, c, d. Выясните, может ли прямоугольник со сторонами a, b уместиться внутри прямоугольника c, d, так чтобы каждая сторона внутреннего прямоугольника была параллельна или перпендикулярна стороне внешнего прямоугольника.",
                        max_length=255,
                        verbose_name="Формулировка  задачи",
                    ),
                ),
                ("a", models.IntegerField(default=1, verbose_name="Значение А")),
                ("b", models.IntegerField(default=1, verbose_name="Значение B")),
                ("c", models.IntegerField(default=1, verbose_name="Значение C")),
                ("d", models.IntegerField(default=1, verbose_name="Значение D")),
                (
                    "result",
                    models.CharField(
                        default="Результат не определен",
                        max_length=255,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "current_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения(save)"
                    ),
                ),
            ],
            options={
                "verbose_name": "A_B_C_Таблица",
                "verbose_name_plural": "A_B_C_Таблицы",
                "ordering": ("-pk",),
            },
        ),
    ]
